name: Deploying to staging

on:
  push:
    branches: [main]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: SSH and deploy to EC2
        run: |
          echo "${{ secrets.SSH_SECRET }}" > ssh_key
          chmod 600 ssh_key

          ssh -tt -o StrictHostKeyChecking=no -o ControlMaster=no -i ssh_key ubuntu@52.66.244.185 << 'EOF'
            set -e

            cd ~/ooooo
            git pull origin main

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            pnpm i
            pnpm run build

            pm2 restart http-server || pm2 start http-server
            pm2 restart ws-server || pm2 start ws-server
            pm2 restart web || pm2 start web
          EOF
